#ifndef PUSHBUTTON_H
#define PUSHBUTTON_H

#define PUSHBUTTON_BIT BIT3
#define SET_PUSHBUTTON_AS_OUTPUT P1OUT |= PUSHBUTTON_BIT
#define INTERRUPT_ON_FALLING_EDGE  P1IES |= PUSHBUTTON_BIT
#define ENABLE_PUSHBUTTON_INTERRUPTS P1IE |= PUSHBUTTON_BIT
#define ENABLE_PULLUP_RESISTOR P1REN |= PUSHBUTTON_BIT


#include <msp430.h>


// Prototypes
void InitializePushButtonPortPin(void);

#endif
